name: Action-demo
on: workflow_dispatch
jobs:
  action-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: aws configure
        uses: aws-actions/aws-configure-aws-credentials@v4
        with:
          aws-secret-key-id: ${{ secrets.AWS-SECRET-ID }}
          aws-access-key-id: ${{ secrets.AWS-ACCESS-ID }}
      - name: Copy index to s3
        run: |
          aws sync ./ s3://bucket-name/ \
          --include "index.html" \
          --exclude "*"
