name: context-demo
on: workflow_dispatch
jobs:
  context-demo:
    runs-on: ubuntu-slim
    steps:
      - name: print who triggered
        run: echo "${{ github.actor }}"
      - name: print all context env
        run: echo "${{ toJson(github) }}"
      - name: print local env
        run: printenv
