#name: Event-based
#on: 
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#    types: opened
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: test
#        run: echo "Hi ${{ vars.NAME }}"
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: secrets
#        run: echo "He loves ${{ secrets.LOVE }}"
