name: if-demo
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: who triggered
        if: github.actor == 'siddharth169'
        run: echo "You are allowed to run ${{ github.actor }}"
      - name: which branch
        if: github.ref_name == 'develop'
        run: echo "You are running in ${{ github.ref_name }}"
